name = "Decs"
desc = "Simple arbitrary precision decimal floating point"
uuid = "27b11802-3905-11e9-3b1d-e1305f76eaae"
authors = ["ScottPJones <scottjones@alum.mit.edu>"]
keywords = ["Decimal", "Floating Point"]
license = "MIT"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["Test", "BenchmarkTools"]
